sudo: required
services: 
  - docker

before install: 
  - docker build -t nikhilgautam/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nikhilgautam/docker-react npm run test -- --coverage